[versions]
kotlinAndroid = "1.8.10"
androidGradlePlugin = "8.2.0-alpha06"
daggerHilt = "2.44"



[libraries]

[plugins]
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
com-android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinAndroid" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }


[bundles]

